version: '3'
volumes:
  mysql-volume:
services:
  mysql:
    image: mysql:8.0
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: GHn9YrDc
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: N5Eg2aPG
      MYSQL_DATABASE: mysql_db
    volumes:
      - mysql-volume:/var/lib/mysql

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # - ./apache/wp/public_html:/var/www/static_files

  # apache:
    # build:
      # context: apache
      # dockerfile: Docker_apache
    # container_name: apache
    # volumes:
      # - ./apache/wp/public_html:/var/www/wordpress.tsiplenkov.ru/public_html
    # ports:
      # - "8090:8081"

  php:
    image: php:7.4-fpm
    container_name: php_container
    volumes:
      - ./php-site:/var/www/html
    depends_on:
      - mysql
