---
all:
  vars:
  hosts:
    ubu-dock:
      ansible_host: 10.0.14.76
      ansible_user: root
      become: true
      become_method: sudo
      ansible_python_interpreter: /usr/bin/python3
    ubu-nginx:
      ansible_host: 10.0.15.134
      ansible_user: andrew
      become: true
      become_method: sudo
      ansible_python_interpreter: /usr/bin/python3
    ubu-apache:
      ansible_host: 10.0.15.135
      ansible_user: andrew
      become: true
      become_method: sudo
      ansible_python_interpreter: /usr/bin/python3
    deb-target:
      ansible_host: 10.0.15.222
      ansible_user: root
      become: true
      become_method: su
      ansible_python_interpreter: /usr/bin/python3
